//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NumberServiceProxy
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="NumberSeriesReturnObject", Namespace="http://tempuri.org/")]
    public partial class NumberSeriesReturnObject : object
    {
        
        private bool inactiveField;
        
        private string currentcodeField;
        
        private string prefixField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool inactive
        {
            get
            {
                return this.inactiveField;
            }
            set
            {
                this.inactiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string currentcode
        {
            get
            {
                return this.currentcodeField;
            }
            set
            {
                this.currentcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string prefix
        {
            get
            {
                return this.prefixField;
            }
            set
            {
                this.prefixField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Interval", Namespace="http://tempuri.org/")]
    public partial class Interval : object
    {
        
        private int lowerField;
        
        private int upperField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int lower
        {
            get
            {
                return this.lowerField;
            }
            set
            {
                this.lowerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int upper
        {
            get
            {
                return this.upperField;
            }
            set
            {
                this.upperField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/", ItemName="string")]
    public class ArrayOfString : System.Collections.Generic.List<string>
    {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NumberServiceProxy.NumberServiceSoap")]
    public interface NumberServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNextNumber", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetNextNumberResponse> GetNextNumberAsync(NumberServiceProxy.GetNextNumberRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentCode", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCodeResponse> GetCurrentCodeAsync(NumberServiceProxy.GetCurrentCodeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentCode_PrefixedAndPadded", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedResponse> GetCurrentCode_PrefixedAndPaddedAsync(NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentCode_PrefixedAndPaddedEnhanced", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedResponse> GetCurrentCode_PrefixedAndPaddedEnhancedAsync(NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCurrentCode_Padded", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCode_PaddedResponse> GetCurrentCode_PaddedAsync(NumberServiceProxy.GetCurrentCode_PaddedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetInterval", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetIntervalResponse> GetIntervalAsync(NumberServiceProxy.GetIntervalRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAlertLevel", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetAlertLevelResponse> GetAlertLevelAsync(NumberServiceProxy.GetAlertLevelRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPrefix", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetPrefixResponse> GetPrefixAsync(NumberServiceProxy.GetPrefixRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNumberSeries", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetNumberSeriesResponse> GetNumberSeriesAsync(NumberServiceProxy.GetNumberSeriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetNumberSeriesXML", ReplyAction="*")]
        System.Threading.Tasks.Task<NumberServiceProxy.GetNumberSeriesXMLResponse> GetNumberSeriesXMLAsync(NumberServiceProxy.GetNumberSeriesXMLRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNextNumberRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNextNumber", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetNextNumberRequestBody Body;
        
        public GetNextNumberRequest()
        {
        }
        
        public GetNextNumberRequest(NumberServiceProxy.GetNextNumberRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNextNumberRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberseriescode;
        
        public GetNextNumberRequestBody()
        {
        }
        
        public GetNextNumberRequestBody(string numberseriescode)
        {
            this.numberseriescode = numberseriescode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNextNumberResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNextNumberResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetNextNumberResponseBody Body;
        
        public GetNextNumberResponse()
        {
        }
        
        public GetNextNumberResponse(NumberServiceProxy.GetNextNumberResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNextNumberResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNextNumberResult;
        
        public GetNextNumberResponseBody()
        {
        }
        
        public GetNextNumberResponseBody(string GetNextNumberResult)
        {
            this.GetNextNumberResult = GetNextNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentCodeRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentCode", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetCurrentCodeRequestBody Body;
        
        public GetCurrentCodeRequest()
        {
        }
        
        public GetCurrentCodeRequest(NumberServiceProxy.GetCurrentCodeRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentCodeRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberseriescode;
        
        public GetCurrentCodeRequestBody()
        {
        }
        
        public GetCurrentCodeRequestBody(string numberseriescode)
        {
            this.numberseriescode = numberseriescode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentCodeResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentCodeResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetCurrentCodeResponseBody Body;
        
        public GetCurrentCodeResponse()
        {
        }
        
        public GetCurrentCodeResponse(NumberServiceProxy.GetCurrentCodeResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentCodeResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentCodeResult;
        
        public GetCurrentCodeResponseBody()
        {
        }
        
        public GetCurrentCodeResponseBody(string GetCurrentCodeResult)
        {
            this.GetCurrentCodeResult = GetCurrentCodeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentCode_PrefixedAndPaddedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentCode_PrefixedAndPadded", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedRequestBody Body;
        
        public GetCurrentCode_PrefixedAndPaddedRequest()
        {
        }
        
        public GetCurrentCode_PrefixedAndPaddedRequest(NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentCode_PrefixedAndPaddedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberseriescode;
        
        public GetCurrentCode_PrefixedAndPaddedRequestBody()
        {
        }
        
        public GetCurrentCode_PrefixedAndPaddedRequestBody(string numberseriescode)
        {
            this.numberseriescode = numberseriescode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentCode_PrefixedAndPaddedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentCode_PrefixedAndPaddedResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedResponseBody Body;
        
        public GetCurrentCode_PrefixedAndPaddedResponse()
        {
        }
        
        public GetCurrentCode_PrefixedAndPaddedResponse(NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentCode_PrefixedAndPaddedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentCode_PrefixedAndPaddedResult;
        
        public GetCurrentCode_PrefixedAndPaddedResponseBody()
        {
        }
        
        public GetCurrentCode_PrefixedAndPaddedResponseBody(string GetCurrentCode_PrefixedAndPaddedResult)
        {
            this.GetCurrentCode_PrefixedAndPaddedResult = GetCurrentCode_PrefixedAndPaddedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentCode_PrefixedAndPaddedEnhancedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentCode_PrefixedAndPaddedEnhanced", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedRequestBody Body;
        
        public GetCurrentCode_PrefixedAndPaddedEnhancedRequest()
        {
        }
        
        public GetCurrentCode_PrefixedAndPaddedEnhancedRequest(NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentCode_PrefixedAndPaddedEnhancedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberseriescode;
        
        public GetCurrentCode_PrefixedAndPaddedEnhancedRequestBody()
        {
        }
        
        public GetCurrentCode_PrefixedAndPaddedEnhancedRequestBody(string numberseriescode)
        {
            this.numberseriescode = numberseriescode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentCode_PrefixedAndPaddedEnhancedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentCode_PrefixedAndPaddedEnhancedResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedResponseBody Body;
        
        public GetCurrentCode_PrefixedAndPaddedEnhancedResponse()
        {
        }
        
        public GetCurrentCode_PrefixedAndPaddedEnhancedResponse(NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentCode_PrefixedAndPaddedEnhancedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NumberServiceProxy.NumberSeriesReturnObject GetCurrentCode_PrefixedAndPaddedEnhancedResult;
        
        public GetCurrentCode_PrefixedAndPaddedEnhancedResponseBody()
        {
        }
        
        public GetCurrentCode_PrefixedAndPaddedEnhancedResponseBody(NumberServiceProxy.NumberSeriesReturnObject GetCurrentCode_PrefixedAndPaddedEnhancedResult)
        {
            this.GetCurrentCode_PrefixedAndPaddedEnhancedResult = GetCurrentCode_PrefixedAndPaddedEnhancedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentCode_PaddedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentCode_Padded", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetCurrentCode_PaddedRequestBody Body;
        
        public GetCurrentCode_PaddedRequest()
        {
        }
        
        public GetCurrentCode_PaddedRequest(NumberServiceProxy.GetCurrentCode_PaddedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentCode_PaddedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberseriescode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string codelength;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public ushort padchar;
        
        public GetCurrentCode_PaddedRequestBody()
        {
        }
        
        public GetCurrentCode_PaddedRequestBody(string numberseriescode, string codelength, ushort padchar)
        {
            this.numberseriescode = numberseriescode;
            this.codelength = codelength;
            this.padchar = padchar;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCurrentCode_PaddedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCurrentCode_PaddedResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetCurrentCode_PaddedResponseBody Body;
        
        public GetCurrentCode_PaddedResponse()
        {
        }
        
        public GetCurrentCode_PaddedResponse(NumberServiceProxy.GetCurrentCode_PaddedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCurrentCode_PaddedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetCurrentCode_PaddedResult;
        
        public GetCurrentCode_PaddedResponseBody()
        {
        }
        
        public GetCurrentCode_PaddedResponseBody(string GetCurrentCode_PaddedResult)
        {
            this.GetCurrentCode_PaddedResult = GetCurrentCode_PaddedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIntervalRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetInterval", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetIntervalRequestBody Body;
        
        public GetIntervalRequest()
        {
        }
        
        public GetIntervalRequest(NumberServiceProxy.GetIntervalRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIntervalRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberseriescode;
        
        public GetIntervalRequestBody()
        {
        }
        
        public GetIntervalRequestBody(string numberseriescode)
        {
            this.numberseriescode = numberseriescode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetIntervalResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetIntervalResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetIntervalResponseBody Body;
        
        public GetIntervalResponse()
        {
        }
        
        public GetIntervalResponse(NumberServiceProxy.GetIntervalResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetIntervalResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NumberServiceProxy.Interval GetIntervalResult;
        
        public GetIntervalResponseBody()
        {
        }
        
        public GetIntervalResponseBody(NumberServiceProxy.Interval GetIntervalResult)
        {
            this.GetIntervalResult = GetIntervalResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlertLevelRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlertLevel", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetAlertLevelRequestBody Body;
        
        public GetAlertLevelRequest()
        {
        }
        
        public GetAlertLevelRequest(NumberServiceProxy.GetAlertLevelRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlertLevelRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberseriescode;
        
        public GetAlertLevelRequestBody()
        {
        }
        
        public GetAlertLevelRequestBody(string numberseriescode)
        {
            this.numberseriescode = numberseriescode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAlertLevelResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAlertLevelResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetAlertLevelResponseBody Body;
        
        public GetAlertLevelResponse()
        {
        }
        
        public GetAlertLevelResponse(NumberServiceProxy.GetAlertLevelResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAlertLevelResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int GetAlertLevelResult;
        
        public GetAlertLevelResponseBody()
        {
        }
        
        public GetAlertLevelResponseBody(int GetAlertLevelResult)
        {
            this.GetAlertLevelResult = GetAlertLevelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrefixRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrefix", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetPrefixRequestBody Body;
        
        public GetPrefixRequest()
        {
        }
        
        public GetPrefixRequest(NumberServiceProxy.GetPrefixRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPrefixRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberseriescode;
        
        public GetPrefixRequestBody()
        {
        }
        
        public GetPrefixRequestBody(string numberseriescode)
        {
            this.numberseriescode = numberseriescode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrefixResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPrefixResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetPrefixResponseBody Body;
        
        public GetPrefixResponse()
        {
        }
        
        public GetPrefixResponse(NumberServiceProxy.GetPrefixResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPrefixResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetPrefixResult;
        
        public GetPrefixResponseBody()
        {
        }
        
        public GetPrefixResponseBody(string GetPrefixResult)
        {
            this.GetPrefixResult = GetPrefixResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNumberSeriesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNumberSeries", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetNumberSeriesRequestBody Body;
        
        public GetNumberSeriesRequest()
        {
        }
        
        public GetNumberSeriesRequest(NumberServiceProxy.GetNumberSeriesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetNumberSeriesRequestBody
    {
        
        public GetNumberSeriesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNumberSeriesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNumberSeriesResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetNumberSeriesResponseBody Body;
        
        public GetNumberSeriesResponse()
        {
        }
        
        public GetNumberSeriesResponse(NumberServiceProxy.GetNumberSeriesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNumberSeriesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public NumberServiceProxy.ArrayOfString GetNumberSeriesResult;
        
        public GetNumberSeriesResponseBody()
        {
        }
        
        public GetNumberSeriesResponseBody(NumberServiceProxy.ArrayOfString GetNumberSeriesResult)
        {
            this.GetNumberSeriesResult = GetNumberSeriesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNumberSeriesXMLRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNumberSeriesXML", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetNumberSeriesXMLRequestBody Body;
        
        public GetNumberSeriesXMLRequest()
        {
        }
        
        public GetNumberSeriesXMLRequest(NumberServiceProxy.GetNumberSeriesXMLRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNumberSeriesXMLRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string numberseriescode;
        
        public GetNumberSeriesXMLRequestBody()
        {
        }
        
        public GetNumberSeriesXMLRequestBody(string numberseriescode)
        {
            this.numberseriescode = numberseriescode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetNumberSeriesXMLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetNumberSeriesXMLResponse", Namespace="http://tempuri.org/", Order=0)]
        public NumberServiceProxy.GetNumberSeriesXMLResponseBody Body;
        
        public GetNumberSeriesXMLResponse()
        {
        }
        
        public GetNumberSeriesXMLResponse(NumberServiceProxy.GetNumberSeriesXMLResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetNumberSeriesXMLResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetNumberSeriesXMLResult;
        
        public GetNumberSeriesXMLResponseBody()
        {
        }
        
        public GetNumberSeriesXMLResponseBody(string GetNumberSeriesXMLResult)
        {
            this.GetNumberSeriesXMLResult = GetNumberSeriesXMLResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface NumberServiceSoapChannel : NumberServiceProxy.NumberServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class NumberServiceSoapClient : System.ServiceModel.ClientBase<NumberServiceProxy.NumberServiceSoap>, NumberServiceProxy.NumberServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public NumberServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(NumberServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), NumberServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(NumberServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(NumberServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public NumberServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetNextNumberResponse> NumberServiceProxy.NumberServiceSoap.GetNextNumberAsync(NumberServiceProxy.GetNextNumberRequest request)
        {
            return base.Channel.GetNextNumberAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetNextNumberResponse> GetNextNumberAsync(string numberseriescode)
        {
            NumberServiceProxy.GetNextNumberRequest inValue = new NumberServiceProxy.GetNextNumberRequest();
            inValue.Body = new NumberServiceProxy.GetNextNumberRequestBody();
            inValue.Body.numberseriescode = numberseriescode;
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetNextNumberAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCodeResponse> NumberServiceProxy.NumberServiceSoap.GetCurrentCodeAsync(NumberServiceProxy.GetCurrentCodeRequest request)
        {
            return base.Channel.GetCurrentCodeAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCodeResponse> GetCurrentCodeAsync(string numberseriescode)
        {
            NumberServiceProxy.GetCurrentCodeRequest inValue = new NumberServiceProxy.GetCurrentCodeRequest();
            inValue.Body = new NumberServiceProxy.GetCurrentCodeRequestBody();
            inValue.Body.numberseriescode = numberseriescode;
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetCurrentCodeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedResponse> NumberServiceProxy.NumberServiceSoap.GetCurrentCode_PrefixedAndPaddedAsync(NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedRequest request)
        {
            return base.Channel.GetCurrentCode_PrefixedAndPaddedAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedResponse> GetCurrentCode_PrefixedAndPaddedAsync(string numberseriescode)
        {
            NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedRequest inValue = new NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedRequest();
            inValue.Body = new NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedRequestBody();
            inValue.Body.numberseriescode = numberseriescode;
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetCurrentCode_PrefixedAndPaddedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedResponse> NumberServiceProxy.NumberServiceSoap.GetCurrentCode_PrefixedAndPaddedEnhancedAsync(NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedRequest request)
        {
            return base.Channel.GetCurrentCode_PrefixedAndPaddedEnhancedAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedResponse> GetCurrentCode_PrefixedAndPaddedEnhancedAsync(string numberseriescode)
        {
            NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedRequest inValue = new NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedRequest();
            inValue.Body = new NumberServiceProxy.GetCurrentCode_PrefixedAndPaddedEnhancedRequestBody();
            inValue.Body.numberseriescode = numberseriescode;
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetCurrentCode_PrefixedAndPaddedEnhancedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCode_PaddedResponse> NumberServiceProxy.NumberServiceSoap.GetCurrentCode_PaddedAsync(NumberServiceProxy.GetCurrentCode_PaddedRequest request)
        {
            return base.Channel.GetCurrentCode_PaddedAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetCurrentCode_PaddedResponse> GetCurrentCode_PaddedAsync(string numberseriescode, string codelength, ushort padchar)
        {
            NumberServiceProxy.GetCurrentCode_PaddedRequest inValue = new NumberServiceProxy.GetCurrentCode_PaddedRequest();
            inValue.Body = new NumberServiceProxy.GetCurrentCode_PaddedRequestBody();
            inValue.Body.numberseriescode = numberseriescode;
            inValue.Body.codelength = codelength;
            inValue.Body.padchar = padchar;
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetCurrentCode_PaddedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetIntervalResponse> NumberServiceProxy.NumberServiceSoap.GetIntervalAsync(NumberServiceProxy.GetIntervalRequest request)
        {
            return base.Channel.GetIntervalAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetIntervalResponse> GetIntervalAsync(string numberseriescode)
        {
            NumberServiceProxy.GetIntervalRequest inValue = new NumberServiceProxy.GetIntervalRequest();
            inValue.Body = new NumberServiceProxy.GetIntervalRequestBody();
            inValue.Body.numberseriescode = numberseriescode;
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetIntervalAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetAlertLevelResponse> NumberServiceProxy.NumberServiceSoap.GetAlertLevelAsync(NumberServiceProxy.GetAlertLevelRequest request)
        {
            return base.Channel.GetAlertLevelAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetAlertLevelResponse> GetAlertLevelAsync(string numberseriescode)
        {
            NumberServiceProxy.GetAlertLevelRequest inValue = new NumberServiceProxy.GetAlertLevelRequest();
            inValue.Body = new NumberServiceProxy.GetAlertLevelRequestBody();
            inValue.Body.numberseriescode = numberseriescode;
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetAlertLevelAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetPrefixResponse> NumberServiceProxy.NumberServiceSoap.GetPrefixAsync(NumberServiceProxy.GetPrefixRequest request)
        {
            return base.Channel.GetPrefixAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetPrefixResponse> GetPrefixAsync(string numberseriescode)
        {
            NumberServiceProxy.GetPrefixRequest inValue = new NumberServiceProxy.GetPrefixRequest();
            inValue.Body = new NumberServiceProxy.GetPrefixRequestBody();
            inValue.Body.numberseriescode = numberseriescode;
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetPrefixAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetNumberSeriesResponse> NumberServiceProxy.NumberServiceSoap.GetNumberSeriesAsync(NumberServiceProxy.GetNumberSeriesRequest request)
        {
            return base.Channel.GetNumberSeriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetNumberSeriesResponse> GetNumberSeriesAsync()
        {
            NumberServiceProxy.GetNumberSeriesRequest inValue = new NumberServiceProxy.GetNumberSeriesRequest();
            inValue.Body = new NumberServiceProxy.GetNumberSeriesRequestBody();
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetNumberSeriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<NumberServiceProxy.GetNumberSeriesXMLResponse> NumberServiceProxy.NumberServiceSoap.GetNumberSeriesXMLAsync(NumberServiceProxy.GetNumberSeriesXMLRequest request)
        {
            return base.Channel.GetNumberSeriesXMLAsync(request);
        }
        
        public System.Threading.Tasks.Task<NumberServiceProxy.GetNumberSeriesXMLResponse> GetNumberSeriesXMLAsync(string numberseriescode)
        {
            NumberServiceProxy.GetNumberSeriesXMLRequest inValue = new NumberServiceProxy.GetNumberSeriesXMLRequest();
            inValue.Body = new NumberServiceProxy.GetNumberSeriesXMLRequestBody();
            inValue.Body.numberseriescode = numberseriescode;
            return ((NumberServiceProxy.NumberServiceSoap)(this)).GetNumberSeriesXMLAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NumberServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NumberServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.NumberServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://rid.validering.infosolutions.se/numberservice.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.NumberServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://rid.validering.infosolutions.se/numberservice.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            NumberServiceSoap,
            
            NumberServiceSoap12,
        }
    }
}
